version: 0.9.17.{build} # pamietaj aby wersja pasowala do wersji w Domki.rc
environment:
  PYTHON: C:\Python35
  MSIProductVersion: "%APPVEYOR_BUILD_VERSION%"
image:
- Visual Studio 2017
configuration: Deploy
before_build:
- cmd: ''
install: 
- "%PYTHON%/Scripts/pip.exe install nose"
build:
  project: Domki.sln
  verbosity: minimal
after_build:
- cmd: xcopy /Y Grafika BIN\Grafika\
test_script: 
- "%PYTHON%/Scripts/nosetests Edytor" 
artifacts:
- path: BIN
  name: Domki
- path: _Instalka\bin\x64\Deploy\Domcraft.msi
  name: Domcraft
deploy:
  provider: GitHub
  auth_token:
    secure: 6c07t+w5tD3WwSEONNH93xO6g2DHgoWg0cO9DjhlYidfNyuUne9ude6gRDpBMb7S
  artifact: /.*\.msi/
  draft: false
  prerelease: false
  on:
    branch: paczki
    APPVEYOR_REPO_TAG: true